<?php
/**
 * @author      Gustavo Rodrigues Francisco <gustavor.francisco@gmail.com>
 * @copyright   2019 Gustavo Rodrigues Francisco (http://www.gustavofrancisco.com.br)
 * @license     http://www.gustavofrancisco.com.br  Copyright
 *
 * @link        http://www.gustavofrancisco.com.br
 */
?>

<div class="field required">
    <input type="checkbox" name="privacy_policy" id="privacy_policy" title="<?= /* @escapeNotVerified */ __('Privacy Policy') ?>" class="input-text" data-validate="{required:true}"/>
    <label for="privacy_policy" class="label">
        <span><?= /* @escapeNotVerified */ __('Yes I was read the <a href="%1">Privacy Policy</a>', $block->getUrl('privacy-policy')) ?></span>
    </label>
</div>
